### ISSUE TITLE
Please allow access to webcam

### ISSUE THREAD

**Issue by sercxanto** [nbuechner/deltachat-snap#2]
Thanks for the integration into the snap store, I just learned that the snap is provided by the community.

Could you please allow camera access for this snap? Otherwise it is not possible to scan the QR code from the mobile and add the desktop software as secondary device.

I crosschecked with the AppImage. The AppImage exectable is able to scan the QR code.

**Comment by nbuechner** [comment]
Please update your snap with `sudo snap refresh deltachat-desktop` and then execute `sudo snap connect deltachat-desktop:camera`

This should enable camera access. This has to be done manually so i also added this command to the snap store description.

**Comment by sercxanto** [comment]
@nbuechner Thanks for the quick fix. I can confirm that it is working now.
