### ISSUE TITLE
snap delta chat's icon in the launcher as a favorite is not the icon in the launcher when running delta chat

### ISSUE THREAD

**Issue by dln949** [nbuechner/deltachat-snap#3]
Delta chat snap version 1.46.1 on Ubuntu 22.04.4 and gnome shell 42.9 running wayland.  

If I make the snap version of delta chat be a favorite on the launcher, when I launch delta chat it creates a separate icon on the launcher for the running instance of delta chat, instead of using the delta chat icon that is the favorite.

**Comment by nbuechner** [comment]
Can you check if today's snap update fixes that? To me it looks fine now.

**Comment by dln949** [comment]
> Can you check if today's snap update fixes that? To me it looks fine now.

Yep, the problem seems to be solved now.
